import Foundation

enum TrustedCertificateChain {
    static let pem: String = #"""
        -----BEGIN CERTIFICATE-----
        MIIBzzCCAYGgAwIBAgIUTW5Kh9P0H4AZCjQuErxeWytDiJ4wBQYDK2VwMF4xCzAJ
        BgNVBAYTAkpQMQ4wDAYDVQQIDAVUb2t5bzETMBEGA1UEBwwKQ2hpeW9kYS1rdTEQ
        MA4GA1UECgwHa2lyaXJpbjEYMBYGA1UEAwwPa2lyaXJpbiBSb290IFIxMB4XDTI2
        MDUzMDEwNDEyNFoXDTM2MDUyNzEwNDEyNFowXDELMAkGA1UEBhMCSlAxDjAMBgNV
        BAgMBVRva3lvMRMwEQYDVQQHDApDaGl5b2RhLWt1MRAwDgYDVQQKDAdraXJpcmlu
        MRYwFAYDVQQDDA1raXJpcmluIENBIEMxMCowBQYDK2VwAyEAYZSUqGh4hBffzeg+
        jAZWdnEEffqMpUcE3B5xWSTkMKWjUzBRMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0O
        BBYEFBK5cOQuIrLDh+bujCso8vwz5IwRMB8GA1UdIwQYMBaAFGaf0zDqqhMyEJ2c
        fObEq5gh/vcYMAUGAytlcANBAHyFlVzfwzy0ihVCuB7DrxZzoVuNDQsWMWYBPatO
        JXQ6mMZWrtgVJbAM4GwiNjcJg6dSGx6g60gLepKWUBrQWwc=
        -----END CERTIFICATE-----
        -----BEGIN CERTIFICATE-----
        MIIB0zCCAYWgAwIBAgIUCLIv9lsw4jG4vSQQ4Y1q3uDdErkwBQYDK2VwMF4xCzAJ
        BgNVBAYTAkpQMQ4wDAYDVQQIDAVUb2t5bzETMBEGA1UEBwwKQ2hpeW9kYS1rdTEQ
        MA4GA1UECgwHa2lyaXJpbjEYMBYGA1UEAwwPa2lyaXJpbiBSb290IFIxMCAXDTI2
        MDUzMDEwMzQyMloYDzIwNTEwNTI0MTAzNDIyWjBeMQswCQYDVQQGEwJKUDEOMAwG
        A1UECAwFVG9reW8xEzARBgNVBAcMCkNoaXlvZGEta3UxEDAOBgNVBAoMB2tpcmly
        aW4xGDAWBgNVBAMMD2tpcmlyaW4gUm9vdCBSMTAqMAUGAytlcAMhABL9hbOLUqoS
        By2T3r5BEE4cK/g1lshKns3vCvkvGByxo1MwUTAdBgNVHQ4EFgQUZp/TMOqqEzIQ
        nZx85sSrmCH+9xgwHwYDVR0jBBgwFoAUZp/TMOqqEzIQnZx85sSrmCH+9xgwDwYD
        VR0TAQH/BAUwAwEB/zAFBgMrZXADQQBmaZTAc61x6WFXJuWOqEix+HZn3DoJcQkv
        5/j42psKRC4c33DEjDlAtfM2x0hx/lkvcjEywmZfadi4lKzRM4sO
        -----END CERTIFICATE-----
        """#

    static let data: Data = Data(pem.utf8)
}
